name: Deploy to Staging

on:
  push:
    branches:
      - main  # Set this to the branch you use for staging releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Staging
      run: |
        ssh -o StrictHostKeyChecking=no user@your-staging-server "cd /path/to/staging && git pull origin main && deploy_commands_here"
